spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: photogramm_user
    password: 1234
    url: jdbc:mysql://localhost:3306/photogramm
  jackson:
     serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
        WRITE_DATES_WITH_ZONE_ID: true
  cache:
    # Of course this is not production configuration.
    cache-names: feed