spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: photogramm_user
    password: 1234
    url: jdbc:mysql://localhost:3306/photogramm
  thymeleaf:
    prefix: classpath:/static/
  http:
    multipart:
      max-file-size: 10MB
application:
    images:
      height: 360
      width: 460
      fs:
        enabled: true
        files-directory: 'photogramm/photo-service/photos/'
        storage-url: 'http://localhost:8080/imgs/'
        format: JPG


